// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RenovaBills.API.Data;

#nullable disable

namespace RenovaBills.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("RenovaBills.API.Models.EnergyData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ConsumptionKwh")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GridAreaId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PricePerKwh")
                        .HasColumnType("decimal(18,6)");

                    b.Property<double>("ProductionKwh")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GridAreaId");

                    b.HasIndex("Timestamp");

                    b.ToTable("EnergyData");
                });

            modelBuilder.Entity("RenovaBills.API.Models.Forecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ForecastDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForecastType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("GridAreaId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PredictedConsumptionKwh")
                        .HasColumnType("decimal(18,6)");

                    b.Property<double>("PredictedPricePerKwh")
                        .HasColumnType("decimal(18,6)");

                    b.Property<double>("PredictedProductionKwh")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("ForecastDate");

                    b.HasIndex("GridAreaId");

                    b.ToTable("Forecasts");
                });

            modelBuilder.Entity("RenovaBills.API.Models.GridArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("decimal(18,6)");

                    b.Property<double>("Longitude")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("GridAreas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SE1",
                            CreatedAt = new DateTime(2025, 7, 9, 3, 54, 34, 168, DateTimeKind.Utc).AddTicks(2190),
                            Description = "Luleå och norrut",
                            Latitude = 65.584818999999996,
                            Longitude = 22.154807999999999,
                            Name = "Norra Sverige"
                        },
                        new
                        {
                            Id = 2,
                            Code = "SE2",
                            CreatedAt = new DateTime(2025, 7, 9, 3, 54, 34, 168, DateTimeKind.Utc).AddTicks(2200),
                            Description = "Sundsvall - Gävle",
                            Latitude = 62.390810999999999,
                            Longitude = 17.306927000000002,
                            Name = "Norra Mellansverige"
                        },
                        new
                        {
                            Id = 3,
                            Code = "SE3",
                            CreatedAt = new DateTime(2025, 7, 9, 3, 54, 34, 168, DateTimeKind.Utc).AddTicks(2200),
                            Description = "Stockholm - Göteborg",
                            Latitude = 59.334591000000003,
                            Longitude = 18.06324,
                            Name = "Södra Mellansverige"
                        },
                        new
                        {
                            Id = 4,
                            Code = "SE4",
                            CreatedAt = new DateTime(2025, 7, 9, 3, 54, 34, 168, DateTimeKind.Utc).AddTicks(2200),
                            Description = "Malmö och söderut",
                            Latitude = 55.604981000000002,
                            Longitude = 13.003822,
                            Name = "Södra Sverige"
                        });
                });

            modelBuilder.Entity("RenovaBills.API.Models.RenovaBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RenovaBills");
                });

            modelBuilder.Entity("RenovaBills.API.Models.EnergyData", b =>
                {
                    b.HasOne("RenovaBills.API.Models.GridArea", "GridArea")
                        .WithMany("EnergyDataRecords")
                        .HasForeignKey("GridAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GridArea");
                });

            modelBuilder.Entity("RenovaBills.API.Models.Forecast", b =>
                {
                    b.HasOne("RenovaBills.API.Models.GridArea", "GridArea")
                        .WithMany("Forecasts")
                        .HasForeignKey("GridAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GridArea");
                });

            modelBuilder.Entity("RenovaBills.API.Models.GridArea", b =>
                {
                    b.Navigation("EnergyDataRecords");

                    b.Navigation("Forecasts");
                });
#pragma warning restore 612, 618
        }
    }
}
